### ISSUE TITLE
CL --> JS/Rust

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [turtl/core-cl#2]
I noticed you switched the core logic from a CL implementation to a JS/Rust implementation, citing HTML5 maintenance issues as the culprit.  Have you by any chance seen the web app work being done by: https://github.com/fukamachi

I ask because I myself am developing a complex web app whose core is written in CL (https://github.com/Bohdan-Khomtchouk/Biochat) and I'm wondering if there are some considerations and/or potential limitations I need to be aware of and should note now (rather than realize later).  I started getting worried when I read your line: "Although the core project is posted, the new server it talks to (NodeJS/Postgres) is not yet public (yes, a fond farewell to Lisp). Stay tuned!" from your `core-rs` repo.

**Comment by orthecreedence** [comment]
Core-cl was never meant to be run in the browser as much as compiled down to a shared library and loaded by a desktop/mobile app. I had some success with this using ECL (and wrote a blog series about it, if you're interested http://turtlapp.tumblr.com/post/83184613020/embedding-lisp-in-node-webkit-part-1). This is what the new rust core achieves...shared library loaded by a desktop app. The nice thing about rust is that it would be possible (not without some effort but possible) to compile the entire core to webassembly and run it directly in the browser if someone wanted to make a web version. This *may* be possible with ECL, but it'll be uncharted territory from what I know, as many things are in the lisp world.

The reason for going with Rust over CL is that Turtl is nagged by a recurring issue with data being undecryptable due to a bug in the way keys are handled. Rust is so strict with data types and how data is used, that it's much harder to make these kinds of mistakes than in javascript (CL as well). It also has a much smaller footprint, and the platforms I want to hit are all first or second class citizens in Rust, where with ECL you'll have to hunt down some obscure articles written by someone who did a weekend project 5 years ago. Not saying CL is bad, but I just don't have as much energy/time to trailblaze anymore.

As far as the [turtl server](https://github.com/turtl/server) (which used to be in CL and is now node), there are a few reasons for the switch. The main reason was that it was becoming more and more difficult to maintain the async empire I set out to build. Things would break, memory leaks would come up, servers would crash and I was always on my own. There are a few members of the CL community who really took an interest in cl-async and the things built on top of it and helped out a *lot* with feedback and code contributions. There were also other members of the community who focused their energy on rebuilding what I did in a limited capacity for various reasons unknown to me. So, cl-async never really reached the critical mass of interest and contributors I hoped it would. The tall and short of it is that without the help of others, the project became too much to maintain on my own. Around the same time, I'd started working with Node, and while Javascript is kind of a joke language, the tooling and the ecosystem are light years ahead of CL. So when I rearchitected Turtl, I figured a server rewrite in node would solve the issues I was having with CL.

At the moment, I'm not really doing anything in CL anymore, and haven't for probably two or three years. It makes me sad because I love the language so much. At some point I want to get into game programming, and I think I'd start using CL again then. I'd want to build the equivalent of npm/cargo/etc. Quicklisp is really convenient, but not being able to pin certain versions of libraries or install dependencies locally or verify via GPG/signatures are really big limitations.

So how is Biochat set up? Is it a desktop app?

**Comment by Bohdan-Khomtchouk** [comment]
Thank you for clarifying these points for me!

Also, thanks for starring the [Biochat](https://github.com/Bohdan-Khomtchouk/Biochat) repo.  As you probably already know, it's not a desktop/mobile app.

P.S. Do you have an email address I can contact you at?

**Comment by orthecreedence** [comment]
Yeah, orthecreedence@gmail.com =]
